### ISSUE TITLE
Install from requirements.txt fails

### ISSUE THREAD

**Issue by aemitos** [shiyanhui/Monguo#3]
Hi.
I've been using Monguo as ORM for an app.
Today I've tried to deploy at heroku but `pip install -r requirements.txt` fails unless I install motor before. 
The fail is logged below:
```
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-22tPQB-build/setup.py", line 15, in <module>
        import monguo
      File "monguo/__init__.py", line 10, in <module>
        from connection import *
      File "monguo/connection.py", line 8, in <module>
        import motor
    ImportError: No module named motor
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/tmp/pip-22tPQB-build/setup.py", line 15, in <module>
    import monguo
  File "monguo/__init__.py", line 10, in <module>
    from connection import *
  File "monguo/connection.py", line 8, in <module>
    import motor
ImportError: No module named motor
```
Any hint to solve this?
Thanks in advance.
André

**Comment by shiyanhui** [comment]
It's my fault not adding motor to the install_requires. thanks.
